version: '3'

services:
  build:
    build: .
    environment: 
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    volumes:
      - .:/usr/local/src/
    stdin_open: true
    tty: true
    working_dir: /usr/local/src